### ISSUE TITLE
React client - Vite does not run on docker

### ISSUE THREAD

**Issue by lakardion** [thinknimble/tn-spa-bootstrapper#182]
```
 > vite

 failed to load config from /app/client/vite.config.ts
 error when starting dev server:
 Error:
 You installed esbuild for another platform than the one you're currently using.
 This won't work because esbuild is written with native code and needs to
 install a platform-specific binary executable.

 Specifically the "esbuild-darwin-arm64" package is present but this platform
 needs the "esbuild-linux-arm64" package instead. People often get into this
 situation by installing esbuild on Windows or macOS and copying "node_modules"
 into a Docker image that runs Linux, or by copying "node_modules" between
 Windows and WSL environments.

 If you are installing with npm, you can try not copying the "node_modules"
 directory when you copy the files over, and running "npm ci" or "npm install"
 on the destination platform after the copy. Or you could consider using yarn
 instead of npm which has built-in support for installing a package on multiple
 platforms simultaneously.

 If you are installing with yarn, you can try listing both this platform and the
 other platform in your ".yarnrc.yml" file using the "supportedArchitectures"
 feature: https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures
 Keep in mind that this means multiple copies of esbuild will be present.

 Another alternative is to use the "esbuild-wasm" package instead, which works
 the same way on all platforms. But it comes with a heavy performance cost and
 can sometimes be 10x slower than the "esbuild" package, so you may also not
 want to do that.
```

ES build seems to be platform specific so if we do npm install in our local and docker tries to use that in a Linux env it won't work.

Need to look at some of the work arounds that are mentioned in the error message above.

**Comment by NC-Fran** [comment]
Unfortunately, it seems like the local `node_modules` folder was being mounted as a volume in the docker container, which means you would get the dependencies for your local machine rather than those for the container itself.

This was not intended behaviour, [this line](https://github.com/thinknimble/tn-spa-bootstrapper/blob/5284c9b8c6fe24e87ee23ab9adabeba9396fa340/%7B%7Bcookiecutter.project_slug%7D%7D/docker-compose.yaml#L48) should have excluded the node_modules folder from being mounted.
However, as you might see, the path is not correct 😱 

[This PR](https://github.com/thinknimble/tn-spa-bootstrapper/pull/195) should fix it (while also adding an explanation of why is this line needed): https://github.com/thinknimble/tn-spa-bootstrapper/pull/195/files#diff-a05abca89f182c8d673cf0819f5b1875a326604d626808ce70aea9a1e1f61c73R49

Please, can you validate it works for you as well?

**Comment by lakardion** [comment]
checked this last week and could run the app fine in docker
