### ISSUE TITLE
Update Docker configs to avoid conflicts between projects

### ISSUE THREAD

**Issue by brunogarciagonzalez** [thinknimble/tn-spa-bootstrapper#70]
project-specific naming, instead of `server`. Because if we have multiple projects locally, there would be collisions in Docker

**Comment by whusterj** [comment]
Just popped in here to note a few things:

First, I like the idea of having project-specific naming. I noticed that Docker seems smart enough to group containers, even if there are naming conflicts:

<img width="1148" alt="Screen Shot 2022-07-20 at 3 28 10 PM" src="https://user-images.githubusercontent.com/1354713/180067008-bbe56999-c9ac-4b8f-968f-db71cd25c1ce.png">

You can see that both of the 'server-1' containers have unique IDs, BUT they are also based on the same "another_test_server" docker image, which shouldn't be the case, so there does appear to be a conflict there.

Second, we also definitely will have an issue with port conflicts. For instance, I cannot run postgres or Django containers for two different projects at one time, because ports 5432 and 8000 will be occupied. So the current workflow would be to shut down all running containers when switching to another project.

**Comment by whusterj** [comment]
Stale.
